version: "3.3"
services:
  dev:
    container_name: demado-dev
    build: .
    entrypoint: npm start
    volumes:
      - ./src:/app/src:rw
      - ./dest:/app/dest:rw
  release:
    container_name: demado-release
    build: .
    entrypoint: npm run release
    volumes:
      - ./src:/app/src:rw
      - ./dest:/app/dest:rw
      - ./release:/app/release:rw
